spring.application.name=cinema2
spring.profiles.active=dev

secret.key=changeme_jwt_secret_key_for_development
url.frontend=http://localhost:3000

spring.datasource.url=jdbc:postgresql://pg-476e5b-williamsosa2703-b53c.c.aivencloud.com:25339/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=changeme_database_password
spring.datasource.hikari.maximum-pool-size=20

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

sendgrid.api.key=changeme_sendgrid_api_key
mail.from=changeme@gmail.com

cloudinary.cloud_name=changeme_cloud_name
cloudinary.api_key=changeme_api_key
cloudinary.api_secret=changeme_api_secret